/**
 * Country list for Overview map filter.
 * Labels match common values in nucigen_events.country (and geo-coordinates).
 */

export const OVERVIEW_COUNTRIES = [
  'France',
  'Germany',
  'United Kingdom',
  'United States',
  'China',
  'Russia',
  'Ukraine',
  'Japan',
  'India',
  'Brazil',
  'Canada',
  'Australia',
  'South Korea',
  'Italy',
  'Spain',
  'Netherlands',
  'Saudi Arabia',
  'UAE',
  'Turkey',
  'South Africa',
  'Israel',
  'Iran',
  'Iraq',
  'Egypt',
  'Poland',
  'Belgium',
  'Switzerland',
  'Singapore',
  'Indonesia',
  'Mexico',
  'Argentina',
  'Chile',
  'Colombia',
  'DRC',
  'Nigeria',
  'Kenya',
  'Ethiopia',
  'Pakistan',
  'Bangladesh',
  'Vietnam',
  'Thailand',
  'Malaysia',
  'Philippines',
  'Taiwan',
  'Hong Kong',
  'Qatar',
  'Kuwait',
  'Lebanon',
  'Jordan',
  'Afghanistan',
  'Myanmar',
] as const;

export type OverviewCountry = (typeof OVERVIEW_COUNTRIES)[number];
