-- ============================================
-- Migration: Create Watchlist Notifications Table
-- ============================================
-- NEW ARCHITECTURE: Real-time notifications for watchlist changes

CREATE TABLE IF NOT EXISTS public.watchlist_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  watchlist_item_id UUID REFERENCES public.watchlists(id) ON DELETE CASCADE,
  
  -- Notification details
  notification_type TEXT NOT NULL CHECK (notification_type IN ('signal', 'event', 'scenario', 'change')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  
  -- Related entities
  related_signal_id UUID,
  related_event_id UUID,
  related_scenario_id UUID,
  
  -- Status
  read BOOLEAN DEFAULT false,
  read_at TIMESTAMP WITH TIME ZONE,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Additional data
  metadata JSONB DEFAULT '{}'
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_watchlist_notifications_user_id ON public.watchlist_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_notifications_watchlist_item_id ON public.watchlist_notifications(watchlist_item_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_notifications_read ON public.watchlist_notifications(read);
CREATE INDEX IF NOT EXISTS idx_watchlist_notifications_created_at ON public.watchlist_notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_watchlist_notifications_user_read ON public.watchlist_notifications(user_id, read);

-- Enable Row Level Security
ALTER TABLE public.watchlist_notifications ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only view their own notifications
-- Note: With Clerk, authentication is handled via service role or API middleware
DO $$
BEGIN
  DROP POLICY IF EXISTS "Users can view their own notifications" ON public.watchlist_notifications;
EXCEPTION WHEN undefined_table THEN
  NULL;
END $$;
CREATE POLICY "Users can view their own notifications"
  ON public.watchlist_notifications
  FOR SELECT
  TO authenticated, anon
  USING (true); -- API middleware will filter by user_id

-- RLS Policy: Users can update their own notifications (mark as read)
DO $$
BEGIN
  DROP POLICY IF EXISTS "Users can update their own notifications" ON public.watchlist_notifications;
EXCEPTION WHEN undefined_table THEN
  NULL;
END $$;
CREATE POLICY "Users can update their own notifications"
  ON public.watchlist_notifications
  FOR UPDATE
  TO authenticated, anon
  USING (true)
  WITH CHECK (true); -- API middleware will validate user_id

-- RLS Policy: Service role can insert notifications (generated by workers)
-- Service role bypasses RLS, so this is mainly for documentation
