-- ============================================
-- Migration: Create Decision Points Table
-- ============================================
-- NEW ARCHITECTURE: Decision Points for Scenarios
-- Links scenarios to actionable decision points

CREATE TABLE IF NOT EXISTS public.decision_points (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Related entities
  scenario_id UUID REFERENCES public.scenario_predictions(id) ON DELETE CASCADE,
  signal_id UUID, -- Reference to signal (can be from market_signals or other sources)
  event_id UUID REFERENCES public.nucigen_events(id) ON DELETE CASCADE,
  
  -- Decision point details
  type TEXT NOT NULL CHECK (type IN ('monitor', 'prepare', 'act')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high')),
  
  -- Status tracking
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in-progress', 'completed', 'cancelled')),
  
  -- Timing
  deadline TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Additional metadata
  metadata JSONB DEFAULT '{}',
  
  -- Ensure at least one related entity
  CONSTRAINT decision_point_has_entity CHECK (
    scenario_id IS NOT NULL OR signal_id IS NOT NULL OR event_id IS NOT NULL
  )
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_decision_points_scenario_id ON public.decision_points(scenario_id);
CREATE INDEX IF NOT EXISTS idx_decision_points_signal_id ON public.decision_points(signal_id);
CREATE INDEX IF NOT EXISTS idx_decision_points_event_id ON public.decision_points(event_id);
CREATE INDEX IF NOT EXISTS idx_decision_points_type ON public.decision_points(type);
CREATE INDEX IF NOT EXISTS idx_decision_points_priority ON public.decision_points(priority);
CREATE INDEX IF NOT EXISTS idx_decision_points_status ON public.decision_points(status);
CREATE INDEX IF NOT EXISTS idx_decision_points_created_at ON public.decision_points(created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.decision_points ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view all decision points (they're derived from public scenarios/signals)
CREATE POLICY "Decision points are viewable by authenticated users"
  ON public.decision_points
  FOR SELECT
  USING (true);

-- RLS Policy: Only service role can insert/update decision points (generated by AI)
-- Service role bypasses RLS, so this is mainly for documentation

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_decision_points_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at
CREATE TRIGGER decision_points_updated_at
  BEFORE UPDATE ON public.decision_points
  FOR EACH ROW
  EXECUTE FUNCTION update_decision_points_updated_at();
